from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        #size factor
        self.window_width = 100
        self.window_height = 100
        self.widgets_width = 100
        self.widgets_height = 100        
        self.widgets_x_axis = 100
        self.widgets_y_axis = 100
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820 + self.window_width, 700 + self.window_height)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        #titles (x position,y position, width, height)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 50, 781 + self.widgets_width, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        #binarize button, combobox (x position,y position, width, height)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 330 + self.widgets_y_axis, 161, 61))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        #open, save (x position,y position, width, height)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 611 + self.widgets_width, 25))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(243, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.layoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        #lables images (x position,y position, width, height)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 88, 781 + self.widgets_width, 231 + self.widgets_height))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget_4)
        self.label.setStyleSheet("border: 1px solid black;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_2.setStyleSheet("border: 1px solid black;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_8.setStyleSheet("border: 1px solid black;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        #histogram title (x position,y position, width, height)
        self.label_6.setGeometry(QtCore.QRect(230, 320 + self.widgets_y_axis, 132 + self.widgets_width, 24))
        self.label_6.setObjectName("label_6")
        self.graphicsView = PlotWidget(self.centralwidget)
        #graphics histogram (x position,y position, width, height)
        self.graphicsView.setGeometry(QtCore.QRect(230, 350 + self.widgets_y_axis, 361 + self.widgets_width, 211 + self.widgets_height))
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Original image"))
        self.label_5.setText(_translate("MainWindow", "Gray image"))
        self.label_9.setText(_translate("MainWindow", "Binary image"))
        self.pushButton_2.setText(_translate("MainWindow", "Binarize image"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Isodata Thresholding"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Fast Isodata Thresholdining"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Otsu Thresholding"))
        self.pushButton.setText(_translate("MainWindow", "Open image"))
        self.pushButton_3.setText(_translate("MainWindow", "Save"))
        self.label_6.setText(_translate("MainWindow", "Histogram"))
