# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        #size factor
        self.window_width = 120
        self.window_height = 120
        self.widgets_width = 100
        self.widgets_height = 100        
        self.widgets_x_axis = 100
        self.widgets_y_axis = 100
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820 + self.window_width, 700 + self.window_height)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        #titles (x position,y position, width, height)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 50, 781 + self.widgets_width, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.layoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        #lables images (x position,y position, width, height)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 88, 781 + self.widgets_width, 231 + self.widgets_height))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget_4)
        self.label.setStyleSheet("border: 1px solid black;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_2.setStyleSheet("border: 1px solid black;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        #histogram title (x position,y position, width, height)
        self.label_6.setGeometry(QtCore.QRect(230, 320 + self.widgets_y_axis, 132 + self.widgets_width, 24))
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        #button1 (x position,y position, width, height)
        self.pushButton.setGeometry(QtCore.QRect(10, 350 + self.widgets_y_axis, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        #textbox (x position,y position, width, height)
        self.lineEdit.setGeometry(QtCore.QRect(760, 380 + self.widgets_y_axis, 91, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        #text box title (x position,y position, width, height)
        self.label_3.setGeometry(QtCore.QRect(630, 350 + self.widgets_y_axis, 280, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        #button2 (x position,y position, width, height)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 380 + self.widgets_y_axis, 111, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Die 1"))
        self.label_9.setText(_translate("MainWindow", "Die 2"))
        self.label_6.setText(_translate("MainWindow", "Histogram"))
        self.pushButton.setText(_translate("MainWindow", "Roll Dice once"))
        self.label_3.setText(_translate("MainWindow", "Enter number of dice rolls (max 1000)"))
        self.pushButton_2.setText(_translate("MainWindow", "Roll Dice"))
